services:

  mysql:
    container_name: mysql
    image: mysql:9.1.0
    restart: always
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '--silent' ]
      interval: 5s
      timeout: 20s
      retries: 3
      start_period: 5s
    networks:
      - strapi
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - strapi
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080

  strapi:
    container_name: strapi
    build:
      context: .
    restart: always
    env_file: .env
    networks:
      - strapi
    ports:
      - 1337:1337
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: mysql
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}

      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      EMAIL_FROM: ${EMAIL_FROM}
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  strapi-data:

networks:
  strapi:
    driver: bridge
